# Default values for atm0s-media-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "ghcr.io/8xff/atm0s-media-server"
  tag: "master"
  pullPolicy: "Always"

# You must provide a valid seed node address
seedAddr: "0@/ip4/192.168.65.3/udp/3001/ip4/192.168.65.3/tcp/3001"

gateway:
  nodeId: 0
  cpuRequest: 50m
  memoryRequest: 100Mi
  logLevel: "info"
  host: gateway.local

  service:
    httpPort: 3000
    sdnPort: 3001

connector:
  enabled: true
  nodeId: 1
  cpuRequest: 50m
  memoryRequest: 100Mi
  mqUri: "nats://nats"
  innerNats:
    enabled: true

  logLevel: "info"
  service:
    httpPort: 3010

rtmp:
  enabled: false
  nodeId: 2
  cpuRequest: 200m
  memoryRequest: 500Mi
  logLevel: "info"

  service:
    httpPort: 3020

webrtc:
  enabled: true
  nodeId: 3
  cpuRequest: 200m
  memoryRequest: 500Mi
  logLevel: "info"

  service:
    httpPort: 3030

sip:
  enabled: false
  nodeId: 4
  cpuRequest: 100m
  memoryRequest: 200Mi
  logLevel: "info"

  service:
    httpPort: 3040
