{{- if .Values.seedAddr }}
{{- if .Values.connector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atm0s-media-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atm0s-media-connector
  template:
    metadata:
      labels:
        app: atm0s-media-connector
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: atm0s-media-connector 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: 
            - --http-port={{ .Values.connector.service.httpPort }}
            {{- if .Values.connector.service.sdnPort }}
            - --sdn-port={{ .Values.connector.service.sdnPort }}
            {{- end }}
            - --node-id={{ .Values.connector.nodeId }}
            - --seeds={{ .Values.seedAddr }}
            - connector
            - --mq-uri={{ .Values.connector.mqUri }}
          env:
            - name: RUST_LOG
              value: {{ .Values.connector.logLevel }}
          
          ports:
            - name: http
              containerPort: {{ .Values.connector.service.httpPort }}
              protocol: TCP
            {{- if .Values.connector.service.sdnPort }}
            - name: sdn
              containerPort: {{ .Values.connector.service.sdnPort }}
              protocol: TCP
            {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /node-info/
          #     port: http
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          resources:
            requests:
              cpu: {{ .Values.connector.cpuRequest }}
              memory: {{ .Values.connector.memoryRequest }}
{{- end }}
{{- end }}