{{- if .Values.seedAddr }}
{{- if .Values.rtmp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atm0s-media-rtmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atm0s-media-rtmp
  template:
    metadata:
      labels:
        app: atm0s-media-rtmp
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: atm0s-media-rtmp 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --seeds={{ .Values.seedAddr }}
            - --http-port={{ .Values.rtmp.service.httpPort }}
            - --sdn-port={{ .Values.rtmp.service.sdnPort }}
            - --node-id={{ .Values.rtmp.nodeId}}
            - rtmp
          env:
            - name: RUST_LOG
              value: {{ .Values.rtmp.logLevel }}

          ports:
            - name: http
              containerPort: {{ .Values.rtmp.service.httpPort }}
              protocol: TCP
            - name: sdn
              containerPort: {{ .Values.rtmp.service.sdnPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /node-info/
          #     port: http
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          resources:
            requests:
              cpu: {{ .Values.rtmp.cpuRequest }}
              memory: {{ .Values.rtmp.memoryRequest }}
{{- end}}
{{- end}}