
kind: Service
apiVersion: v1
metadata:
  name: gateway
spec:
  selector:
    app: atm0s-media-gateway
  ports:
    - protocol: TCP
      port: {{ .Values.gateway.service.httpPort }}
      targetPort: http
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atm0s-media-gateway
spec:
  selector:
    matchLabels:
      app: atm0s-media-gateway
  template:
    metadata:
      labels:
        app: atm0s-media-gateway
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - am0s-media-gateway
            topologyKey: "kubernetes.io/hostname"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: atm0s-media-gateway 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: 
            - gateway
          env:
            - name: RUST_LOG
              value: {{ .Values.gateway.logLevel }}
            - name: HTTP_PORT
              value: {{ .Values.gateway.service.httpPort | quote}}
            - name: SDN_PORT
              value: {{ .Values.gateway.service.sdnPort | quote }}
            - name: NODE_ID
              value: {{ .Values.gateway.nodeId | quote }}
            {{- if .Values.secure.enabled }}
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: atm0s-cluster-secret
                  key: secret
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.gateway.service.httpPort }}
              protocol: TCP
            - name: sdn
              containerPort: {{ .Values.gateway.service.sdnPort }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.gateway.cpuRequest }}
              memory: {{ .Values.gateway.memoryRequest }}
      
